"""Generate comprehensive threat intelligence reports."""

import json
from datetime import datetime, timezone
from pathlib import Path

from config import GITHUB_REPO, REPORTS_DIR


class ReportGenerator:
    def generate_markdown(self, data: dict) -> str:
        d = data
        name = d.get("honeypot_name", "unknown")
        hp_type = d.get("honeypot_type", "unknown")
        timeframe = d.get("timeframe_hours", 24)
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        summary = d.get("summary", {})
        ttps = d.get("ttps", [])
        iocs = d.get("iocs", [])
        threat_intel = d.get("threat_intel", {})
        sigma_rules = d.get("sigma_rules", [])
        correlation = d.get("correlation", {})

        # IP reputation table
        ip_rows = ""
        for entry in threat_intel.get("ip_results", [])[:15]:
            abuse = entry.get("abuse_score", "N/A")
            feodo = "YES" if entry.get("feodo_c2") else "no"
            ip_rows += f"| {entry.get('ip','')} | {entry.get('country_code','?')} | {entry.get('isp','')} | {abuse} | {feodo} |\n"

        # TTP table
        ttp_rows = ""
        for ttp in ttps:
            ttp_rows += f"| [{ttp['technique_id']}]({ttp['attack_url']}) | {ttp['technique_name']} | {ttp['tactic_name']} | {ttp['severity'].upper()} | {ttp['evidence_count']} |\n"

        # IOC sections
        ip_iocs = [i for i in iocs if i["type"] == "ip"]
        hash_iocs = [i for i in iocs if i["type"] in ("hash_md5", "hash_sha256")]
        cred_iocs = [i for i in iocs if i["type"] == "credential"]
        cmd_iocs = [i for i in iocs if i["type"] == "command"]
        url_iocs = [i for i in iocs if i["type"] == "url"]

        ip_list = "\n".join(f"- `{i['value']}` (seen {i['count']}x)" for i in ip_iocs[:20])
        hash_list = "\n".join(f"- `{i['value']}` ({i['type']})" for i in hash_iocs[:10])
        cred_list = "\n".join(f"- `{i['value']}` (tried {i['count']}x)" for i in cred_iocs[:20])
        cmd_list = "\n".join(f"- `{i['value'][:100]}`" for i in cmd_iocs[:15])
        url_list = "\n".join(f"- `{i['value'][:100]}`" for i in url_iocs[:10])

        # Sigma rules section
        sigma_section = ""
        for rule in sigma_rules[:3]:
            sigma_section += f"\n### Rule: {rule.get('technique_id','')}\n\n```yaml\n{rule.get('sigma_yaml','')}\n```\n"

        # Kill chain
        kill_chain_section = ""
        for stage in correlation.get("kill_chain_stages", []):
            techs = ", ".join(t["technique_id"] for t in stage["techniques"])
            kill_chain_section += f"- **{stage['stage']}**: {techs}\n"

        sophistication = correlation.get("sophistication_label", "Unknown")
        soph_score = correlation.get("sophistication_score", 0)

        md = f"""# Honeypot Threat Intelligence Report

**Honeypot:** `{name}` (type: `{hp_type}`)
**Report Period:** Last {timeframe} hours
**Generated:** {ts}
**Source:** [{GITHUB_REPO}]({GITHUB_REPO})

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Total Events | {summary.get('total_events', 0)} |
| Unique Source IPs | {summary.get('unique_ips', 0)} |
| Connection Attempts | {summary.get('connection_attempts', summary.get('total_requests', 0))} |
| Successful Logins | {summary.get('successful_logins', 0)} |
| Commands Executed | {summary.get('commands_executed', 0)} |
| Files Downloaded | {summary.get('files_downloaded', summary.get('malware_downloads', 0))} |
| TTPs Identified | {len(ttps)} |
| IOCs Extracted | {len(iocs)} |
| Sophistication | **{sophistication}** ({soph_score}%) |

---

## Attacker IP Reputation

| IP | Country | ISP | AbuseIPDB Score | Feodo C2 |
|----|---------|-----|-----------------|----------|
{ip_rows or "| No IPs correlated | | | | |\n"}

---

## Identified TTPs (MITRE ATT&CK)

| Technique ID | Name | Tactic | Severity | Evidence |
|---|---|---|---|---|
{ttp_rows or "| No TTPs detected | | | | |\n"}

### Kill Chain Coverage

{kill_chain_section or "*No kill chain stages identified.*"}

---

## Extracted IOCs

### IP Addresses ({len(ip_iocs)})
{ip_list or "*None extracted.*"}

### File Hashes ({len(hash_iocs)})
{hash_list or "*None extracted.*"}

### URLs / C2 Endpoints ({len(url_iocs)})
{url_list or "*None extracted.*"}

### Observed Credentials ({len(cred_iocs)})
{cred_list or "*None extracted.*"}

### Commands Executed ({len(cmd_iocs)})
{cmd_list or "*None extracted.*"}

---

## Generated Sigma Rules
{sigma_section or "*No Sigma rules generated.*"}

---

## Raw Statistics

```json
{json.dumps(summary, indent=2)}
```

---

*Generated by [HPThreat MCP Server]({GITHUB_REPO})*
"""
        return md

    def generate_json(self, data: dict) -> str:
        return json.dumps(data, indent=2, default=str)

    def save(self, content: str, honeypot_name: str, fmt: str) -> Path:
        ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        ext = "md" if fmt == "markdown" else "json"
        path = REPORTS_DIR / f"{honeypot_name}_{ts}.{ext}"
        path.write_text(content, encoding="utf-8")
        return path
